# Generated by Django 5.0.6 on 2024-08-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0014_alter_cutofbanana_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cutofbanana',
            old_name='date',
            new_name='data',
        ),
    ]
