# Generated by Django 5.0.6 on 2024-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0015_rename_date_cutofbanana_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutofbanana',
            name='cotacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cutofbanana',
            name='qtd_total',
            field=models.IntegerField(default=0),
        ),
    ]
