# Generated by Django 5.0.6 on 2024-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas', '0016_cutofbanana_cotacao_cutofbanana_qtd_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutofbanana',
            name='preco_total',
            field=models.FloatField(default=0.0),
        ),
    ]
